name: Publish Package

# **What it does**: Creates and Publishes our docker images for later deployment
# **Why we have it**: We need the iamges to create deployments

on:
  workflow_run:
    workflows:
      - Test
    branches: [main]
    types:
      - completed

jobs:
  publish:
    name: Update Documenation/Package Version then Publish
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_ACTIONS }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}